// vue-js-test/src/components/AppBar.vue
<template>
  <nav class="app-bar">
    <div class="nav-container">
      <div class="logo">My App</div>
      <div class="nav-links">
        <router-link to="/" class="nav-link">Home</router-link>
        <router-link to="/test" class="nav-link">Test</router-link>
        <router-link to="/example" class="nav-link">Example</router-link>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: "AppBar",
};
</script>

<style scoped>
.app-bar {
  background-color: #2563eb;
  padding: 16px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.nav-container {
  max-width: 1200px;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.logo {
  color: white;
  font-size: 1.5rem;
  font-weight: bold;
}

.nav-links {
  display: flex;
  gap: 16px;
}

.nav-link {
  color: white;
  text-decoration: none;
  font-size: 1rem;
}

.nav-link:hover {
  color: #bfdbfe;
}
</style>

// my-react-app/src/components/AppBar.jsx
import React from 'react';
import { Link } from 'react-router-dom';

const AppBar = () => (
	<nav
		style={{
			position: 'fixed',
			top: 0,
			left: 0,
			width: '100%',
			background: '#1976d2',
			color: 'white',
			padding: '1rem',
			zIndex: 1000,
			display: 'flex',
			justifyContent: 'center',
			boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
		}}
	>
		<Link
			to="/shoppingCart/test"
			style={{
				marginRight: '1rem',
				color: 'white',
				textDecoration: 'none',
				fontWeight: 500,
			}}
		>
			쇼핑카트 테스트
		</Link>
		<Link
			to="/shoppingCart/example"
			style={{
				marginRight: '1rem',
				color: 'white',
				textDecoration: 'none',
				fontWeight: 500,
			}}
		>
			쇼핑카트 예시
		</Link>
	</nav>
);

export default AppBar;
